version: '2'
engines:
  duplication:
    enabled: true
    config:
      languages:
        - kotlin
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 300
  method-complexity:
    enabled: true
    config:
      threshold: 8
  method-count:
    enabled: true
    config:
      threshold: 30
  method-lines:
    enabled: true
    config:
      threshold: 30
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 5
  similar-code:
    enabled: true
    config:
      threshold: 70
  identical-code:
    enabled: true
    config:
      threshold: 70
exclude_patterns:
  - '**/commonTest/'
